  import sys
    import os
    import pytest
    
    sys.path.append(
    os.path.abspath(
    os.path.join(
    os.path.dirname(__file__),
    ".."
    )
    )
    )
    
    
    from src.connection.destination_connection import get_destination_connection
    
    from src.validation.data_quality import (
    check_table_exists,
    check_row_count,
    check_null_values,
    check_duplicate_records
    )
    
    from src.utils.config_loader import load_config
    
    
    config = load_config()
    
    
    @pytest.fixture(scope="module")
  def cursor():

    connection = get_destination_connection()
    cursor = connection.cursor()

    yield cursor

    cursor.close()
    connection.close()
    
    
    @pytest.mark.parametrize(
    "table_name",
    config["tables"]
    )
  def test_table_exists(cursor, table_name):

    result = check_table_exists(
    cursor,
    table_name
    )

    assert result == "PASS"
    
    
    @pytest.mark.parametrize(
    "table_name",
    config["row_count_checks"]
    )
  def test_row_count(cursor, table_name):

    result = check_row_count(
    cursor,
    table_name
    )

    assert result == "PASS"
    
    
    @pytest.mark.parametrize(
    "null_check",
    config["null_checks"]
    )
  def test_null_checks(cursor, null_check):

    result = check_null_values(
    cursor,
    null_check["table"],
    null_check["column"]
    )

    assert result == "PASS"
    
    
    @pytest.mark.parametrize(
    "duplicate_check",
    config["duplicate_checks"]
    )
  def test_duplicate_checks(cursor, duplicate_check):

    result = check_duplicate_records(
    cursor,
    duplicate_check["table"],
    duplicate_check["column"]
    )

    assert result == "PASS"